@SET OUTPUT_NAME=parabola_demo
emcc -I../include -std=c++11 -DPLATFORM_WEB -DGRAPHICS_API_OPENGL_ES2 -DMODULE_NAME=%OUTPUT_NAME% -s WASM=1 -s USE_GLFW=3 -s MODULARIZE=1 -s EXPORT_NAME='%OUTPUT_NAME%' -O2 main.cpp ../lib/raylib.bc -o %OUTPUT_NAME%.js
